/** Helper chunk to get the PCF soft shadow generated by all the {@link core/lights/DirectionalLight.DirectionalLight | DirectionalLight} and {@link core/lights/PointLight.PointLight | PointLight}. */
export const getPCFShadows: string = /* wgsl */ `
  let pointShadows = getPCFPointShadows(worldPosition);
  let directionalShadows = getPCFDirectionalShadows(worldPosition);
`
