/** Helper chunk to get the PCF soft shadow generated by all the {@link DirectionalLight} and {@link PointLight}. */
export const getPCFShadows: string = /* wgsl */ `
  let pointShadows = getPCFPointShadows(worldPosition);
  let directionalShadows = getPCFDirectionalShadows(worldPosition);
`